version: "3"

volumes:
  mongo_customer_data_aras:
    driver: local

services:
  customer-backend-api-aras:
    container_name: customer-admin-panel-api-aras
    build:
      context: ./backend-api/sample-backend
      dockerfile: Dockerfile
    ports:
      - "41300:3000"
    networks:
      - profolio-customer-network-aras
  customer-admin-panel-aras:
    container_name: customer-admin-panel-aras
    build:
      context: ./admin-panel
      dockerfile: Dockerfile
    ports:
      - "41301:3000"
    volumes:
      - ./admin-panel/src:/app/src
      - ./admin-panel/public:/app/public
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BACKEND_BASE_URL=http://localhost:40000
    networks:
      - profolio-customer-network-aras
  profolio-customer-mongodb-aras:
    container_name: profolio-customer-mongodb-aras
    image: mongo
    volumes:
      - mongo_customer_data_aras:/data/db
    networks:
      - profolio-customer-network-aras

networks:
  profolio-customer-network-aras:
    driver: bridge
