version: "3"

services:
  customer-admin-panel:
    container_name: customer-admin-panel-profolio-dev
    build:
      context: ./admin-panel
      dockerfile: Dockerfile.dev
    ports:
      - "3100:3000"
    volumes:
      - ./admin-panel/src:/app/src
      - ./admin-panel/public:/app/public
    environment:
      - CHOKIDAR_USEPOLLING=true
