version: "3"

volumes:
  mongo_customer_data:
    driver: local

services:
  customer-admin-panel:
    container_name: customer-admin-panel-profolio-dev
    build:
      context: ./admin-panel
      dockerfile: Dockerfile
    ports:
      - "3100:3000"
    volumes:
      - ./admin-panel/src:/app/src
      - ./admin-panel/public:/app/public
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BACKEND_BASE_URL=http://localhost:9000
    networks:
      - profolio-customer-network
  customer-admin-panel-api:
    container_name: customer-admin-panel-api
    build:
      context: ./backend-microservices/sample-backend
      dockerfile: Dockerfile
    ports:
      - "8001:3000"
    networks:
      - profolio-customer-network
  profolio-customer-mongodb:
    container_name: profolio-customer-mongodb
    image: mongo
    volumes:
      - mongo_customer_data:/data/db
    networks:
      - profolio-customer-network

networks:
  profolio-customer-network:
    driver: bridge
