version: "3"

volumes:
  mongo_customer_data_google:
    driver: local

services:
  customer-backend-api-google:
    container_name: customer-admin-panel-api-google
    build:
      context: ./backend-api/sample-backend
      dockerfile: Dockerfile
    ports:
      - "41200:3000"
    networks:
      - profolio-customer-network-google
  customer-admin-panel-google:
    container_name: customer-admin-panel-google
    build:
      context: ./admin-panel
      dockerfile: Dockerfile
    ports:
      - "41201:3000"
    volumes:
      - ./admin-panel/src:/app/src
      - ./admin-panel/public:/app/public
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BACKEND_BASE_URL=http://localhost:40000
    networks:
      - profolio-customer-network-google
  profolio-customer-mongodb-google:
    container_name: profolio-customer-mongodb-google
    image: mongo
    volumes:
      - mongo_customer_data_google:/data/db
    networks:
      - profolio-customer-network-google

networks:
  profolio-customer-network-google:
    driver: bridge
